# Generated by Django 2.1.1 on 2018-09-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorManager', '0002_delete_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('commandState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorManager.CommandState')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorManager.Vendor')),
            ],
        ),
    ]
