# Generated by Django 2.1.1 on 2018-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorManager', '0003_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
