# Generated by Django 2.1.1 on 2018-09-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objectManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('ticketObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateTime', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketManager.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketManager.TicketState'),
        ),
    ]
