# Generated by Django 2.1.1 on 2018-09-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManager', '0003_ticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='TicketState',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
