# Generated by Django 2.1.1 on 2018-09-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManager', '0005_auto_20180919_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketState',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
        migrations.DeleteModel(
            name='TicketState',
        ),
    ]
