# Generated by Django 2.1.1 on 2018-09-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketManager', '0007_auto_20180919_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticketState',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
        migrations.DeleteModel(
            name='TicketState',
        ),
    ]
