# Generated by Django 2.1.1 on 2018-09-25 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('depth', models.IntegerField()),
                ('objectIn', models.ManyToManyField(blank=True, related_name='_object_objectIn_+', to='objectManager.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=3)),
                ('mendatory', models.BooleanField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='objectdatatype',
            name='objectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType'),
        ),
        migrations.AddField(
            model_name='objectdata',
            name='objectDataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectDataType'),
        ),
        migrations.AddField(
            model_name='object',
            name='objectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType'),
        ),
    ]
