# Generated by Django 2.1.1 on 2018-09-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectManager', '0002_delete_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('objectIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
            ],
        ),
    ]
