# Generated by Django 2.1.1 on 2018-09-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectManager', '0003_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='objectIn',
        ),
        migrations.DeleteModel(
            name='ObjectData',
        ),
        migrations.DeleteModel(
            name='ObjectDataType',
        ),
        migrations.DeleteModel(
            name='ObjectType',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
