# Generated by Django 2.1.1 on 2018-09-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objectManager', '0004_auto_20180919_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('objectIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=3)),
                ('mendatory', models.BooleanField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('objectIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType')),
            ],
        ),
        migrations.AddField(
            model_name='objectdatatype',
            name='objectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType'),
        ),
        migrations.AddField(
            model_name='objectdata',
            name='objectDataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectDataType'),
        ),
        migrations.AddField(
            model_name='object',
            name='objectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType'),
        ),
    ]
