# Generated by Django 2.1.1 on 2018-09-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyManager', '0008_auto_20180919_1415'),
        ('ticketManager', '0010_auto_20180919_1415'),
        ('objectManager', '0005_auto_20180919_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='objectIn',
        ),
        migrations.RemoveField(
            model_name='object',
            name='objectType',
        ),
        migrations.RemoveField(
            model_name='objectdata',
            name='item',
        ),
        migrations.RemoveField(
            model_name='objectdata',
            name='objectDataType',
        ),
        migrations.RemoveField(
            model_name='objectdatatype',
            name='objectType',
        ),
        migrations.RemoveField(
            model_name='objecttype',
            name='objectIn',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='ObjectData',
        ),
        migrations.DeleteModel(
            name='ObjectDataType',
        ),
        migrations.DeleteModel(
            name='ObjectType',
        ),
    ]
