# Generated by Django 2.1.1 on 2018-09-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorManager', '0003_command'),
        ('userManager', '0003_auto_20180919_1336'),
        ('objectManager', '0006_auto_20180919_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorManager.Command')),
                ('objectIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=3)),
                ('mendatory', models.BooleanField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('objectIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType')),
            ],
        ),
        migrations.AddField(
            model_name='objectdatatype',
            name='objectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType'),
        ),
        migrations.AddField(
            model_name='objectdata',
            name='objectDataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectDataType'),
        ),
        migrations.AddField(
            model_name='object',
            name='objectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.ObjectType'),
        ),
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.User'),
        ),
    ]
