# Generated by Django 2.1.1 on 2018-09-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectManager', '0007_auto_20180919_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='objectIn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object'),
        ),
        migrations.AlterField(
            model_name='objectdata',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
