# Generated by Django 2.1.1 on 2018-09-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historyManager', '0002_delete_objecthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateField()),
                ('position', models.CharField(max_length=512)),
                ('objectState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historyManager.ObjectState')),
            ],
        ),
    ]
