# Generated by Django 2.1.1 on 2018-09-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManager', '0003_auto_20180919_1336'),
        ('historyManager', '0004_auto_20180919_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateField()),
                ('position', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='objecthistory',
            name='objectState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historyManager.ObjectState'),
        ),
        migrations.AddField(
            model_name='objecthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.User'),
        ),
    ]
