# Generated by Django 2.1.1 on 2018-09-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyManager', '0005_auto_20180919_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecthistory',
            name='objectState',
        ),
        migrations.RemoveField(
            model_name='objecthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ObjectHistory',
        ),
    ]
