# Generated by Django 2.1.1 on 2018-09-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0003_auto_20180919_1336'),
        ('objectManager', '0005_auto_20180919_1346'),
        ('historyManager', '0006_auto_20180919_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('ref', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateField()),
                ('position', models.CharField(max_length=512)),
                ('objectShown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object')),
                ('objectState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historyManager.ObjectState')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.User')),
            ],
        ),
    ]
