# Generated by Django 2.1.1 on 2018-09-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyManager', '0007_objecthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecthistory',
            name='objectShown',
        ),
        migrations.RemoveField(
            model_name='objecthistory',
            name='objectState',
        ),
        migrations.RemoveField(
            model_name='objecthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ObjectHistory',
        ),
        migrations.DeleteModel(
            name='ObjectState',
        ),
    ]
