# Generated by Django 2.1.1 on 2018-09-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManager', '0003_auto_20180919_1336'),
        ('historyManager', '0009_objecthistory_objectstate'),
        ('objectManager', '0007_auto_20180919_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecthistory',
            name='objectShown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectManager.Object'),
        ),
        migrations.AddField(
            model_name='objecthistory',
            name='objectState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historyManager.ObjectState'),
        ),
        migrations.AddField(
            model_name='objecthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.User'),
        ),
    ]
