# Generated by Django 2.1.1 on 2018-09-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyManager', '0010_auto_20180919_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecthistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
