# Generated by Django 2.1.2 on 2018-10-26 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommandState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('depth', models.IntegerField()),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Command')),
                ('objectIn', models.ManyToManyField(blank=True, related_name='_object_objectIn_+', to='core.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=3)),
                ('mendatory', models.BooleanField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('position', models.CharField(max_length=512)),
                ('objectShown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateTime', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('oAuthKey', models.CharField(max_length=1024)),
                ('entryDate', models.DateField(blank=True, null=True)),
                ('outDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=512)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserJob'),
        ),
        migrations.AddField(
            model_name='user',
            name='userRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserRole'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Object'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TicketState'),
        ),
        migrations.AddField(
            model_name='objecthistory',
            name='objectState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ObjectState'),
        ),
        migrations.AddField(
            model_name='objecthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='objectdatatype',
            name='objectType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ObjectType'),
        ),
        migrations.AddField(
            model_name='objectdata',
            name='objectDataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ObjectDataType'),
        ),
        migrations.AddField(
            model_name='object',
            name='objectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ObjectType'),
        ),
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='command',
            name='commandState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CommandState'),
        ),
        migrations.AddField(
            model_name='command',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vendor'),
        ),
    ]
