# Generated by Django 2.1.1 on 2018-09-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('oAuthKey', models.CharField(max_length=1024)),
                ('entryDate', models.DateField(blank=True, null=True)),
                ('outDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.UserJob'),
        ),
        migrations.AddField(
            model_name='user',
            name='userRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.UserRole'),
        ),
    ]
