# Generated by Django 2.1.1 on 2018-09-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserJob',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
