# Generated by Django 2.1.1 on 2018-09-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManager', '0002_auto_20180919_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('OAuthKey', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.UserJob'),
        ),
        migrations.AddField(
            model_name='user',
            name='userRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.UserRole'),
        ),
    ]
